{{- if .Values.enabled -}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todofrontend.fullname" . }}-pdb
  labels:
    {{- include "todofrontend.labels" . | nindent 4 }}

spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  
  selector:
    matchLabels:
      {{- include "todofrontend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}