---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: registry-pusher
spec:
  deletionPolicy: Orphan
  forProvider:
    name: registry-pusher
    folderIdRef:
      name: {{ .Values.folder }}


---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: registry-pusher
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: registry-pusher
    role: container-registry.images.pusher
    folderIdRef:
      name: {{ .Values.folder }}

---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: registry-puller
spec:
  deletionPolicy: Orphan
  forProvider:
    name: registry-puller
    folderIdRef:
      name: {{ .Values.folder }}

---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: registry-puller
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: registry-puller
    role: container-registry.images.puller
    folderIdRef:
      name: {{ .Values.folder }}
---

apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: monitoring
spec:
  deletionPolicy: Orphan
  forProvider:
    name: monitoring
    folderIdRef:
      name: {{ .Values.folder }}

---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: monitoring
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: monitoring
    role: monitoring.editor
    folderIdRef:
      name: {{ .Values.folder }}

---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: logging
spec:
  deletionPolicy: Orphan
  forProvider:
    name: logging
    folderIdRef:
      name: {{ .Values.folder }}

---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: logging-writer
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: logging
    role: logging.writer
    folderIdRef:
      name: {{ .Values.folder }}


apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: logging-mon-editor
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: logging
    role: monitoring.editor
    folderIdRef:
      name: {{ .Values.folder }}
