{{- if .Values.enabled -}}
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "todobackend.fullname" . }}-hpa
  labels:
    {{- include "todobackend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "todobackend.fullname" . }}-api
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- range .Values.hpa.metrics }}
    - {{- . | toYaml | nindent 6 -}}
    {{- end }}
{{- end }}
{{- end }}