apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    name: {{ include "metric-provider.fullname" . }}
    namespace: {{ .Release.Namespace }}
    port: 443
  version: v1beta1