apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metric-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  ymTokenServiceaccountJson: {{ .Values.yandexMetrics.token.serviceAccountJson | b64enc }}
  ymTokenUrl: {{ .Values.yandexMetrics.token.url | b64enc }}