{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metric-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
  selector:
    app: {{ include "metric-provider.fullname" . }}
  type: {{ .Values.service.serviceType }}
{{- end }}